# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Alamofire_JSON_API' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Alamofire_JSON_API
  pod 'Alamofire', '~> 4.0.0-beta.4'

end
